url: "https://pyukey.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/bio" # the subpath of your site, e.g. /blog
title: "ANdrey" # the name of your site, e.g. ACME Corp.
jekyll-minifier:
  uglifier_args:
    harmony: true
plugins:
  - jekyll-minifier
